### ISSUE TITLE
setup-python stepがない

### ISSUE THREAD

**Issue by na0fu3y** [rhoboro/github-actions#16]
現状、setup-pythonを実行しておらず、ubuntu-latestのpip3に依存している。
setup-pythonでベースイメージに依らず、python環境を構築できる他、バージョン固定できるのでおすすめです。

```yaml
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
```

<a href="https://github.com/actions/setup-python">actions/setup-python</a>

```html
<a href="https://github.com/actions/setup-python">actions/setup-python</a>
```
